### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by elifoster** [RX14/Computer-Science-AS-2015#1]
Java does not have variable interpolation, however, it does have string formatting. e.g.,

``` java
System.out.println(String.format("A rectangle with the size of %d x %d has an area of %d", width, height, area));
```

Or an even cleaner version:

``` java
System.out.format("A rectangle with the size of %d x %d has an area of %d", width, height, area);
```

I would pr but a) I'm on my phone and b) this is your school stuff

**Comment by RX14** [comment]
I know it does, and the string formatting is even more of a pain to use.

**Comment by RX14** [comment]
Also this kind of line-by line comment is what diff comments are for.

**Comment by elifoster** [comment]
Except that I can't be bothered to go look at every commit in the repository until I find the right one (probably two, since there are two times where you could've used it). It makes the code more readable, not sure about it being more annoying than the standard java bullshit
